### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by FrannDzs** [BigETI/sampcmd#1]
![image](https://user-images.githubusercontent.com/76663897/192171006-bf5128a5-f407-4016-91f8-d0ae2eea1fe5.png)

I have a lot of problems using this with other plugins. Can it be made more friendly with other mods?
Also, when I try to run SAMP 0.3DL without any mod and sampcmd, it runs GTA SA instead of SAMP. any ideas?

**Comment by BigETI** [comment]
This issue is not related to this tool. sampcmd just launches GTA San Andreas and injects samp.dll into the newly created process, nothing more.

Try re-installing your game and run it without any additional mods.

**Comment by FrannDzs** [comment]
> This issue is not related to this tool. sampcmd just launches GTA San Andreas and injects samp.dll into the newly created process, nothing more.
> 
> Try re-installing your game and run it without any additional mods.

This is working now, thanks!
pd: I reinstalled everything again even now with mods I don't have that error anymore.

A colleague has the same error I had, so I guess reinstalling everything from scratch will fix it.

It is some incompatibility not yet discovered.

If I find out what it was I will inform you.

Regards!
